<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="27" passed="15" failed="12" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-02-07T20:57:34 CET" name="Command line suite" finished-at="2022-02-07T20:59:17 CET" duration-ms="103722">
    <groups>
      <group name="Retesting">
        <method signature="TestEmailInvalidDomain.validCredentials()[pri:0, instance:Tests.Register.Cases.Retesting.TestEmailInvalidDomain@407b8435]" name="validCredentials" class="Tests.Register.Cases.Retesting.TestEmailInvalidDomain"/>
        <method signature="TestNSymbolsForSurname.validCredentials()[pri:0, instance:Tests.Register.Cases.Retesting.TestNSymbolsForSurname@1282e98]" name="validCredentials" class="Tests.Register.Cases.Retesting.TestNSymbolsForSurname"/>
        <method signature="TestNumbersForName.validCredentials()[pri:0, instance:Tests.Register.Cases.Retesting.TestNumbersForName@4db0ba1c]" name="validCredentials" class="Tests.Register.Cases.Retesting.TestNumbersForName"/>
        <method signature="TestNumbersForSurname.validCredentials()[pri:0, instance:Tests.Register.Cases.Retesting.TestNumbersForSurname@1d91fa02]" name="validCredentials" class="Tests.Register.Cases.Retesting.TestNumbersForSurname"/>
        <method signature="TestPasswordLimit.validCredentials()[pri:0, instance:Tests.Register.Cases.Retesting.TestPasswordLimit@1578fa9]" name="validCredentials" class="Tests.Register.Cases.Retesting.TestPasswordLimit"/>
        <method signature="TestSymbolsForName.validCredentials()[pri:0, instance:Tests.Register.Cases.Retesting.TestSymbolsForName@414b2df5]" name="validCredentials" class="Tests.Register.Cases.Retesting.TestSymbolsForName"/>
      </group> <!-- Retesting -->
      <group name="Regresion">
        <method signature="TestAcademySelection.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestAcademySelection@40d96578]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestAcademySelection"/>
        <method signature="TestAcademySelectionMandatory.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestAcademySelectionMandatory@c97721b]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestAcademySelectionMandatory"/>
        <method signature="TestAcademySelectionOnlyOne.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestAcademySelectionOnlyOne@283ab206]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestAcademySelectionOnlyOne"/>
        <method signature="TestBiographyMandatory.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestBiographyMandatory@35fa450f]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestBiographyMandatory"/>
        <method signature="TestContinueRegistrationFourthForm.flowTest()[pri:0, instance:Tests.Register.Cases.Regresion.TestContinueRegistrationFourthForm@3e03046d]" name="flowTest" class="Tests.Register.Cases.Regresion.TestContinueRegistrationFourthForm"/>
        <method signature="TestContinueRegistrationSecondForm.flowTest()[pri:0, instance:Tests.Register.Cases.Regresion.TestContinueRegistrationSecondForm@9b3be1c]" name="flowTest" class="Tests.Register.Cases.Regresion.TestContinueRegistrationSecondForm"/>
        <method signature="TestContinueRegistrationThirdForm.flowTest()[pri:0, instance:Tests.Register.Cases.Regresion.TestContinueRegistrationThirdForm@74e497ae]" name="flowTest" class="Tests.Register.Cases.Regresion.TestContinueRegistrationThirdForm"/>
        <method signature="TestEmailInvalidDomain.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestEmailInvalidDomain@13516600]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestEmailInvalidDomain"/>
        <method signature="TestEmailMandatory.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestEmailMandatory@35d7386b]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestEmailMandatory"/>
        <method signature="TestNSymbolsForSurname.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestNSymbolsForSurname@69f080ad]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestNSymbolsForSurname"/>
        <method signature="TestNameMandatory.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestNameMandatory@21002393]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestNameMandatory"/>
        <method signature="TestNextButton.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestNextButton@718989fa]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestNextButton"/>
        <method signature="TestNumbersForName.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestNumbersForName@6568f998]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestNumbersForName"/>
        <method signature="TestNumbersForSurname.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestNumbersForSurname@45d4421d]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestNumbersForSurname"/>
        <method signature="TestPasswordLimit.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestPasswordLimit@782fd504]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestPasswordLimit"/>
        <method signature="TestPasswordMandatory.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestPasswordMandatory@1537c744]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestPasswordMandatory"/>
        <method signature="TestSkillSelectLimit.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestSkillSelectLimit@37314843]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestSkillSelectLimit"/>
        <method signature="TestSkillSelectMin.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestSkillSelectMin@50122012]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestSkillSelectMin"/>
        <method signature="TestSurnameMandatory.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestSurnameMandatory@569348e1]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestSurnameMandatory"/>
        <method signature="TestSymbolsForName.validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestSymbolsForName@7db5b890]" name="validCredentials" class="Tests.Register.Cases.Regresion.TestSymbolsForName"/>
      </group> <!-- Regresion -->
      <group name="Flow">
        <method signature="TestPositiveFlow.flowTest()[pri:0, instance:Tests.Register.Cases.KeyFlow.TestPositiveFlow@1860a7a1]" name="flowTest" class="Tests.Register.Cases.KeyFlow.TestPositiveFlow"/>
      </group> <!-- Flow -->
    </groups>
    <test started-at="2022-02-07T20:57:34 CET" name="Command line test" finished-at="2022-02-07T20:59:17 CET" duration-ms="103722">
      <class name="Tests.Register.Cases.Regresion.TestNextButton">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestNextButton@718989fa]" started-at="2022-02-07T20:58:19 CET" name="validCredentials" finished-at="2022-02-07T20:58:23 CET" duration-ms="3835" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
      </class> <!-- Tests.Register.Cases.Regresion.TestNextButton -->
      <class name="Tests.Register.Cases.Regresion.TestEmailInvalidDomain">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestEmailInvalidDomain@13516600]" started-at="2022-02-07T20:58:11 CET" name="validCredentials" finished-at="2022-02-07T20:58:13 CET" duration-ms="2151" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Tests.Register.Cases.Regresion.TestEmailInvalidDomain.validCredentials(TestEmailInvalidDomain.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestEmailInvalidDomain@13516600]" started-at="2022-02-07T20:58:13 CET" name="tearDown" finished-at="2022-02-07T20:58:14 CET" duration-ms="597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestEmailInvalidDomain -->
      <class name="Tests.Register.Cases.Regresion.TestPasswordLimit">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestPasswordLimit@782fd504]" started-at="2022-02-07T20:58:34 CET" name="validCredentials" finished-at="2022-02-07T20:58:37 CET" duration-ms="3932" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Tests.Register.Cases.Regresion.TestPasswordLimit.validCredentials(TestPasswordLimit.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestPasswordLimit@782fd504]" started-at="2022-02-07T20:58:37 CET" name="tearDown" finished-at="2022-02-07T20:58:38 CET" duration-ms="602" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestPasswordLimit -->
      <class name="Tests.Register.Cases.Regresion.TestAcademySelectionOnlyOne">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestAcademySelectionOnlyOne@283ab206]" started-at="2022-02-07T20:57:49 CET" name="validCredentials" finished-at="2022-02-07T20:57:52 CET" duration-ms="2689" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestAcademySelectionOnlyOne@283ab206]" started-at="2022-02-07T20:57:52 CET" name="tearDown" finished-at="2022-02-07T20:57:52 CET" duration-ms="581" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestAcademySelectionOnlyOne -->
      <class name="Tests.Register.Cases.Regresion.TestContinueRegistrationThirdForm">
        <test-method signature="flowTest()[pri:0, instance:Tests.Register.Cases.Regresion.TestContinueRegistrationThirdForm@74e497ae]" started-at="2022-02-07T20:58:06 CET" name="flowTest" finished-at="2022-02-07T20:58:10 CET" duration-ms="4513" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flowTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestContinueRegistrationThirdForm@74e497ae]" started-at="2022-02-07T20:58:10 CET" name="tearDown" finished-at="2022-02-07T20:58:11 CET" duration-ms="597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestContinueRegistrationThirdForm -->
      <class name="Tests.Register.Cases.Regresion.TestAcademySelection">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestAcademySelection@40d96578]" started-at="2022-02-07T20:57:41 CET" name="validCredentials" finished-at="2022-02-07T20:57:45 CET" duration-ms="4003" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestAcademySelection@40d96578]" started-at="2022-02-07T20:57:45 CET" name="tearDown" finished-at="2022-02-07T20:57:46 CET" duration-ms="593" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestAcademySelection -->
      <class name="Tests.Register.Cases.Regresion.TestEmailMandatory">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestEmailMandatory@35d7386b]" started-at="2022-02-07T20:58:14 CET" name="validCredentials" finished-at="2022-02-07T20:58:16 CET" duration-ms="2068" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestEmailMandatory@35d7386b]" started-at="2022-02-07T20:58:16 CET" name="tearDown" finished-at="2022-02-07T20:58:16 CET" duration-ms="581" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestEmailMandatory -->
      <class name="Tests.Register.Cases.Regresion.TestPasswordMandatory">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestPasswordMandatory@1537c744]" started-at="2022-02-07T20:58:38 CET" name="validCredentials" finished-at="2022-02-07T20:58:41 CET" duration-ms="3142" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestPasswordMandatory@1537c744]" started-at="2022-02-07T20:58:41 CET" name="tearDown" finished-at="2022-02-07T20:58:42 CET" duration-ms="581" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestPasswordMandatory -->
      <class name="Tests.Register.Cases.Retesting.TestNumbersForSurname">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Retesting.TestNumbersForSurname@1d91fa02]" started-at="2022-02-07T20:59:09 CET" name="validCredentials" finished-at="2022-02-07T20:59:11 CET" duration-ms="2196" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Tests.Register.Cases.Retesting.TestNumbersForSurname.validCredentials(TestNumbersForSurname.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Retesting.TestNumbersForSurname@1d91fa02]" started-at="2022-02-07T20:59:11 CET" name="tearDown" finished-at="2022-02-07T20:59:11 CET" duration-ms="663" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Retesting.TestNumbersForSurname -->
      <class name="Tests.Register.Cases.Regresion.TestNSymbolsForSurname">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestNSymbolsForSurname@69f080ad]" started-at="2022-02-07T20:58:23 CET" name="validCredentials" finished-at="2022-02-07T20:58:26 CET" duration-ms="2736" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Tests.Register.Cases.Regresion.TestNSymbolsForSurname.validCredentials(TestNSymbolsForSurname.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestNSymbolsForSurname@69f080ad]" started-at="2022-02-07T20:58:26 CET" name="tearDown" finished-at="2022-02-07T20:58:26 CET" duration-ms="604" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestNSymbolsForSurname -->
      <class name="Tests.Register.Cases.Regresion.TestAcademySelectionMandatory">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestAcademySelectionMandatory@c97721b]" started-at="2022-02-07T20:57:46 CET" name="validCredentials" finished-at="2022-02-07T20:57:48 CET" duration-ms="2455" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestAcademySelectionMandatory@c97721b]" started-at="2022-02-07T20:57:48 CET" name="tearDown" finished-at="2022-02-07T20:57:49 CET" duration-ms="579" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestAcademySelectionMandatory -->
      <class name="Tests.Register.Cases.Regresion.TestSurnameMandatory">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestSurnameMandatory@569348e1]" started-at="2022-02-07T20:58:54 CET" name="validCredentials" finished-at="2022-02-07T20:58:56 CET" duration-ms="2110" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestSurnameMandatory@569348e1]" started-at="2022-02-07T20:58:56 CET" name="tearDown" finished-at="2022-02-07T20:58:57 CET" duration-ms="635" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestSurnameMandatory -->
      <class name="Tests.Register.Cases.Regresion.TestBiographyMandatory">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestBiographyMandatory@35fa450f]" started-at="2022-02-07T20:57:52 CET" name="validCredentials" finished-at="2022-02-07T20:57:54 CET" duration-ms="2070" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestBiographyMandatory@35fa450f]" started-at="2022-02-07T20:57:54 CET" name="tearDown" finished-at="2022-02-07T20:57:55 CET" duration-ms="582" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestBiographyMandatory -->
      <class name="Tests.Register.Cases.KeyFlow.TestPositiveFlow">
        <test-method is-config="true" signature="init()[pri:0, instance:Tests.Register.Cases.KeyFlow.TestPositiveFlow@1860a7a1]" started-at="2022-02-07T20:57:34 CET" name="init" finished-at="2022-02-07T20:57:35 CET" duration-ms="1099" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="flowTest()[pri:0, instance:Tests.Register.Cases.KeyFlow.TestPositiveFlow@1860a7a1]" started-at="2022-02-07T20:57:35 CET" name="flowTest" finished-at="2022-02-07T20:57:41 CET" duration-ms="5966" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flowTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.KeyFlow.TestPositiveFlow@1860a7a1]" started-at="2022-02-07T20:57:41 CET" name="tearDown" finished-at="2022-02-07T20:57:41 CET" duration-ms="598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.KeyFlow.TestPositiveFlow -->
      <class name="Tests.Register.Cases.Regresion.TestContinueRegistrationSecondForm">
        <test-method signature="flowTest()[pri:0, instance:Tests.Register.Cases.Regresion.TestContinueRegistrationSecondForm@9b3be1c]" started-at="2022-02-07T20:58:01 CET" name="flowTest" finished-at="2022-02-07T20:58:05 CET" duration-ms="4190" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flowTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestContinueRegistrationSecondForm@9b3be1c]" started-at="2022-02-07T20:58:05 CET" name="tearDown" finished-at="2022-02-07T20:58:06 CET" duration-ms="590" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestContinueRegistrationSecondForm -->
      <class name="Tests.Register.Cases.Retesting.TestNumbersForName">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Retesting.TestNumbersForName@4db0ba1c]" started-at="2022-02-07T20:59:06 CET" name="validCredentials" finished-at="2022-02-07T20:59:08 CET" duration-ms="2108" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Tests.Register.Cases.Retesting.TestNumbersForName.validCredentials(TestNumbersForName.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Retesting.TestNumbersForName@4db0ba1c]" started-at="2022-02-07T20:59:08 CET" name="tearDown" finished-at="2022-02-07T20:59:09 CET" duration-ms="643" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Retesting.TestNumbersForName -->
      <class name="Tests.Register.Cases.Regresion.TestSkillSelectMin">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestSkillSelectMin@50122012]" started-at="2022-02-07T20:58:49 CET" name="validCredentials" finished-at="2022-02-07T20:58:54 CET" duration-ms="5147" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestSkillSelectMin@50122012]" started-at="2022-02-07T20:58:54 CET" name="tearDown" finished-at="2022-02-07T20:58:54 CET" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestSkillSelectMin -->
      <class name="Tests.Register.Cases.Regresion.TestNumbersForSurname">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestNumbersForSurname@45d4421d]" started-at="2022-02-07T20:58:31 CET" name="validCredentials" finished-at="2022-02-07T20:58:33 CET" duration-ms="2287" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Tests.Register.Cases.Regresion.TestNumbersForSurname.validCredentials(TestNumbersForSurname.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestNumbersForSurname@45d4421d]" started-at="2022-02-07T20:58:33 CET" name="tearDown" finished-at="2022-02-07T20:58:34 CET" duration-ms="626" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestNumbersForSurname -->
      <class name="Tests.Register.Cases.Retesting.TestEmailInvalidDomain">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Retesting.TestEmailInvalidDomain@407b8435]" started-at="2022-02-07T20:59:00 CET" name="validCredentials" finished-at="2022-02-07T20:59:02 CET" duration-ms="2156" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Tests.Register.Cases.Retesting.TestEmailInvalidDomain.validCredentials(TestEmailInvalidDomain.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Retesting.TestEmailInvalidDomain@407b8435]" started-at="2022-02-07T20:59:02 CET" name="tearDown" finished-at="2022-02-07T20:59:03 CET" duration-ms="598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Retesting.TestEmailInvalidDomain -->
      <class name="Tests.Register.Cases.Regresion.TestSkillSelectLimit">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestSkillSelectLimit@37314843]" started-at="2022-02-07T20:58:42 CET" name="validCredentials" finished-at="2022-02-07T20:58:49 CET" duration-ms="6879" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestSkillSelectLimit@37314843]" started-at="2022-02-07T20:58:49 CET" name="tearDown" finished-at="2022-02-07T20:58:49 CET" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestSkillSelectLimit -->
      <class name="Tests.Register.Cases.Regresion.TestNumbersForName">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestNumbersForName@6568f998]" started-at="2022-02-07T20:58:26 CET" name="validCredentials" finished-at="2022-02-07T20:58:30 CET" duration-ms="3871" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Tests.Register.Cases.Regresion.TestNumbersForName.validCredentials(TestNumbersForName.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestNumbersForName@6568f998]" started-at="2022-02-07T20:58:30 CET" name="tearDown" finished-at="2022-02-07T20:58:31 CET" duration-ms="597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestNumbersForName -->
      <class name="Tests.Register.Cases.Retesting.TestSymbolsForName">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Retesting.TestSymbolsForName@414b2df5]" started-at="2022-02-07T20:59:14 CET" name="validCredentials" finished-at="2022-02-07T20:59:17 CET" duration-ms="2400" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Tests.Register.Cases.Retesting.TestSymbolsForName.validCredentials(TestSymbolsForName.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Retesting.TestSymbolsForName@414b2df5]" started-at="2022-02-07T20:59:17 CET" name="tearDown" finished-at="2022-02-07T20:59:17 CET" duration-ms="661" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Retesting.TestSymbolsForName -->
      <class name="Tests.Register.Cases.Retesting.TestPasswordLimit">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Retesting.TestPasswordLimit@1578fa9]" started-at="2022-02-07T20:59:11 CET" name="validCredentials" finished-at="2022-02-07T20:59:14 CET" duration-ms="2215" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Tests.Register.Cases.Retesting.TestPasswordLimit.validCredentials(TestPasswordLimit.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Retesting.TestPasswordLimit@1578fa9]" started-at="2022-02-07T20:59:14 CET" name="tearDown" finished-at="2022-02-07T20:59:14 CET" duration-ms="597" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Retesting.TestPasswordLimit -->
      <class name="Tests.Register.Cases.Regresion.TestNameMandatory">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestNameMandatory@21002393]" started-at="2022-02-07T20:58:16 CET" name="validCredentials" finished-at="2022-02-07T20:58:18 CET" duration-ms="2130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestNameMandatory@21002393]" started-at="2022-02-07T20:58:18 CET" name="tearDown" finished-at="2022-02-07T20:58:19 CET" duration-ms="583" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestNameMandatory -->
      <class name="Tests.Register.Cases.Regresion.TestSymbolsForName">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Regresion.TestSymbolsForName@7db5b890]" started-at="2022-02-07T20:58:57 CET" name="validCredentials" finished-at="2022-02-07T20:59:00 CET" duration-ms="3079" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Tests.Register.Cases.Regresion.TestSymbolsForName.validCredentials(TestSymbolsForName.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestSymbolsForName@7db5b890]" started-at="2022-02-07T20:59:00 CET" name="tearDown" finished-at="2022-02-07T20:59:00 CET" duration-ms="611" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestSymbolsForName -->
      <class name="Tests.Register.Cases.Regresion.TestContinueRegistrationFourthForm">
        <test-method signature="flowTest()[pri:0, instance:Tests.Register.Cases.Regresion.TestContinueRegistrationFourthForm@3e03046d]" started-at="2022-02-07T20:57:55 CET" name="flowTest" finished-at="2022-02-07T20:58:00 CET" duration-ms="5620" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flowTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Regresion.TestContinueRegistrationFourthForm@3e03046d]" started-at="2022-02-07T20:58:00 CET" name="tearDown" finished-at="2022-02-07T20:58:01 CET" duration-ms="585" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Regresion.TestContinueRegistrationFourthForm -->
      <class name="Tests.Register.Cases.Retesting.TestNSymbolsForSurname">
        <test-method signature="validCredentials()[pri:0, instance:Tests.Register.Cases.Retesting.TestNSymbolsForSurname@1282e98]" started-at="2022-02-07T20:59:03 CET" name="validCredentials" finished-at="2022-02-07T20:59:05 CET" duration-ms="2115" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Tests.Register.Cases.Retesting.TestNSymbolsForSurname.validCredentials(TestNSymbolsForSurname.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.Register.Cases.Retesting.TestNSymbolsForSurname@1282e98]" started-at="2022-02-07T20:59:05 CET" name="tearDown" finished-at="2022-02-07T20:59:06 CET" duration-ms="635" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.Register.Cases.Retesting.TestNSymbolsForSurname -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
